### ISSUE TITLE
Please publish the source code of 0x08dd4c804399ee591c725b4a35c0e249bc1a6e83 on Etherscan.

### ISSUE THREAD

**Issue by ytrezq** [bZxNetwork/bZx-monorepo#15]
Obviously, this contract is used to manage withdrawals of the Vault through Delegatecall… Would it be possible to at least know what’s it’s source code in this GitHub repository if not publishing it on Etherscan ?

**Comment by tomcbean** [comment]
This points to this contract https://github.com/bZxNetwork/bZx-monorepo/blob/a4f7b478e252ebf1e4a853abbc31d6d202f084ef/packages/contracts/contracts/modules/LoanHealth_MiscFunctions4.sol.
